baseurl: ""
url: "http://dashboard.prorealnost.com"
markdown: kramdown
exclude:
  - node_modules
  - package.json
  - README.md
  - gulpfile.js
  - '*.scss'

permalink: /:title/

trello_app_key: 37315bf8eb45a3ecc104908ef64e22df
